### ISSUE TITLE
IndexError: list index out of range during installing

### ISSUE THREAD

**Issue by timegate** [JiayuZou2020/DiffBEV#3]
Hello, I tried below codes
cd mmsegmentation
pip install -v -e .

but it seems there's no mmsegmentation folder, and "pip install -v -e ." gives me "IndexError: list index out of range" in line 56 (info['package'] = line.split('#egg=')[1]).

Could anyone let me know how to fix this please?

**Comment by JiayuZou2020** [comment]
Hi～Please try the following code
cd DiffBEV
pip install -v -e .
We have fixed the installation pipeline in the [README.md](https://github.com/jiayuzou2020/diffbev#readme).
