### ISSUE TITLE
How to train DiffBEV model?

### ISSUE THREAD

**Issue by AMagd** [JiayuZou2020/DiffBEV#6]
Thanks for open-sourcing your work!
Since you didn't mention anything about how to train the model, and by looking at the files uploaded, I couldn't figure how to train your model, so I was wondering if you have uploaded the files related to training DiffBEV or not yet. Would you please clarify this?

**Comment by JiayuZou2020** [comment]
Thanks for your attention to our work. Recently, we are working with other projects. In the near future, the training and testing files and running commands will be updated in the Readme file.
